import { readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

const ROOT = resolve(import.meta.dirname, '..')
const MAP_DATA_PATH = resolve(ROOT, 'src', 'data', 'mapData.ts')
const DEFAULT_OUTPUT_PATH = resolve(ROOT, 'src', 'data', 'detectedFixtures.ts')

const DEFAULT_HEIGHT_MAP = {
  bookshelf: 2.34,
  counter: 1.1,
  displayLow: 0.9,
}

function parseArgs(argv) {
  const args = {
    input: null,
    output: DEFAULT_OUTPUT_PATH,
    dryRun: false,
  }

  for (let i = 2; i < argv.length; i++) {
    const token = argv[i]
    if (token === '--input') args.input = argv[i + 1]
    if (token === '--output') args.output = argv[i + 1]
    if (token === '--dry-run') args.dryRun = true
  }

  if (!args.input) {
    throw new Error('Missing required argument: --input <detected_fixtures.json>')
  }
  if (!args.output) {
    throw new Error('Missing value for --output')
  }
  return args
}

function parseMapDimensions(tsSource) {
  const widthMatch = tsSource.match(/export const mapWidth = ([0-9.+-]+)/)
  const depthMatch = tsSource.match(/export const mapDepth = ([0-9.+-]+)/)
  if (!widthMatch || !depthMatch) {
    throw new Error('Could not parse mapWidth/mapDepth from src/data/mapData.ts')
  }
  return {
    mapWidth: Number(widthMatch[1]),
    mapDepth: Number(depthMatch[1]),
  }
}

function normalizeClassName(value) {
  return String(value ?? '')
    .trim()
    .toLowerCase()
    .replaceAll(/\s+/g, '')
}

function classToKind(rawClass) {
  const normalized = normalizeClassName(rawClass)
  if (!normalized) return null
  if (normalized === 'bookshelf') return 'bookshelf'
  if (normalized === 'shelf/counter' || normalized === 'shelfcounter' || normalized === 'counter') return 'counter'
  if (normalized === 'table/display' || normalized === 'tabledisplay' || normalized === 'display' || normalized === 'table') return 'displayLow'
  return null
}

function toRounded(value, digits) {
  const p = 10 ** digits
  return Math.round(value * p) / p
}

function pickDetections(payload) {
  if (Array.isArray(payload)) return payload
  if (Array.isArray(payload?.objects)) return payload.objects
  if (Array.isArray(payload?.detections)) return payload.detections
  return []
}

function pickImageSize(payload) {
  const candidates = [
    payload?.source_image,
    payload?.image,
    payload?.meta?.source_image,
    payload?.meta?.image,
  ]
  for (const c of candidates) {
    const width = Number(c?.width)
    const height = Number(c?.height)
    if (Number.isFinite(width) && Number.isFinite(height) && width > 0 && height > 0) {
      return { width, height }
    }
  }
  return { width: 0, height: 0 }
}

function convertDetections({ detections, image, mapWidth, mapDepth }) {
  if (image.width <= 0 || image.height <= 0) {
    throw new Error('Image width/height missing in JSON. Add source_image.width and source_image.height.')
  }

  const converted = []
  const rejected = []

  for (const [index, raw] of detections.entries()) {
    const kind = classToKind(raw.class)
    const rect = raw.rotated_rect
    const center = rect?.center
    const size = rect?.size

    if (!kind) {
      rejected.push({ index, reason: `unknown class: ${raw.class}` })
      continue
    }
    if (!Array.isArray(center) || center.length < 2 || !Array.isArray(size) || size.length < 2) {
      rejected.push({ index, reason: 'missing rotated_rect.center/size' })
      continue
    }

    const cxPx = Number(center[0])
    const cyPx = Number(center[1])
    const wPx = Math.abs(Number(size[0]))
    const dPx = Math.abs(Number(size[1]))
    const angleDeg = Number(rect?.angle ?? 0)
    const score = Number(raw.score)

    if (![cxPx, cyPx, wPx, dPx, angleDeg].every(Number.isFinite)) {
      rejected.push({ index, reason: 'center/size/angle is not finite number' })
      continue
    }
    if (wPx <= 0 || dPx <= 0) {
      rejected.push({ index, reason: 'size has non-positive side' })
      continue
    }

    const cx = (cxPx / image.width - 0.5) * mapWidth
    const cz = (cyPx / image.height - 0.5) * mapDepth
    const w = (wPx / image.width) * mapWidth
    const d = (dPx / image.height) * mapDepth

    converted.push({
      kind,
      cx: toRounded(cx, 3),
      cz: toRounded(cz, 3),
      w: toRounded(w, 3),
      d: toRounded(d, 3),
      yaw: toRounded((-angleDeg * Math.PI) / 180, 4),
      h: DEFAULT_HEIGHT_MAP[kind],
      sourceClass: String(raw.class ?? ''),
      ...(Number.isFinite(score) ? { score: toRounded(score, 4) } : {}),
    })
  }

  return { converted, rejected }
}

function toTsModule({ source, image, converted }) {
  return `// Auto-generated by scripts/convertDetectedFixtures.mjs
// Source: ${source}
// Run: node scripts/convertDetectedFixtures.mjs --input <detected_fixtures.json>

export type DetectedFixtureKind = 'bookshelf' | 'counter' | 'displayLow'

export type DetectedFixture = {
  kind: DetectedFixtureKind
  cx: number
  cz: number
  w: number
  d: number
  yaw: number
  h: number
  score?: number
  sourceClass?: string
}

export const DETECTED_FIXTURE_SOURCE = ${JSON.stringify(source)}
export const DETECTED_IMAGE_SIZE = ${JSON.stringify(image)}
export const detectedFixtures: DetectedFixture[] = ${JSON.stringify(converted)}
`
}

async function main() {
  const args = parseArgs(process.argv)
  const inputPath = resolve(ROOT, args.input)
  const outputPath = resolve(ROOT, args.output)
  const payload = JSON.parse(readFileSync(inputPath, 'utf-8'))
  const mapDataSource = readFileSync(MAP_DATA_PATH, 'utf-8')
  const { mapWidth, mapDepth } = parseMapDimensions(mapDataSource)
  const detections = pickDetections(payload)
  const image = pickImageSize(payload)

  const { converted, rejected } = convertDetections({
    detections,
    image,
    mapWidth,
    mapDepth,
  })
  const tsModule = toTsModule({
    source: args.input,
    image,
    converted,
  })

  if (args.dryRun) {
    console.log(`[dry-run] detections=${detections.length} converted=${converted.length} rejected=${rejected.length}`)
  } else {
    writeFileSync(outputPath, tsModule, 'utf-8')
    console.log(`Wrote ${outputPath}`)
    console.log(`detections=${detections.length} converted=${converted.length} rejected=${rejected.length}`)
  }

  if (rejected.length > 0) {
    console.log('Rejected entries:')
    for (const entry of rejected) {
      console.log(`  - #${entry.index}: ${entry.reason}`)
    }
  }
}

main().catch((error) => {
  console.error(error)
  process.exit(1)
})
